services:
  app:
    build: .
    environment:
      DATABASE_HOST: db
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: password
      DATABASE_NAME: cardtrading_development
    tty: true
    ports:
      - "3100:3000"
    volumes:
      - app_data:/rails/tmp
      - app_data:/rails/log
      - .:/rails
      - /rails/node_modules
    networks:
      - cardtrading
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: cardtrading_development
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "13100:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - cardtrading
    restart: always
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db-data:
    driver: local
  app_data:
    driver: local
networks:
  cardtrading:
    driver: bridge
